Sas 40 resources backend
ducth1903/sas-period-tracker pull request #42
Opened 2023-05-14 21:35 UTC by nhan0504

Paginate the resources return when get resources by category
Test all API with postman
Create a new database name sas-resource in postgresql instead of using the default database with db name postgres

2023-06-04 18:02 UTC, ducth1903 requested changes, later dismissed
Looks good! Please remove the commented function in `periods.py` if not needed anymore.
Let's also squash commit into one. Feel free to ping @21pdavis or other colleagues for review afterwards if I am not available.

2023-06-10 02:16 UTC, 21pdavis approved these changes
All set to merge!

2023-06-10 02:16 UTC, 21pdavis commented on server/api/v0/routes/periods.py
The changes in this file seem unnecessary to me. I'm worried that in making these changes without being able to easily test them (we'd have to replace the deployed server on AWS), we may run into problems later down the line. I think we should revert this file back to the way that it was. I think the new structure is good, but since the old one worked, I don't think it's worth changing at this point. There also seems to be some functions missing the `method` parameter for their route call.

@nhan0504 are there any changes here that aren't purely structural? i.e., changes that are new features and support the resource backend in some way that the previous `periods.py` did not? If no new features and only formatting changes, either you or I should revert it, I think.

2023-06-10 02:18 UTC, 21pdavis commented
Squashing first, then merging.

2023-06-10 02:19 UTC, merged